### ISSUE TITLE
Infinite loop with some faces

### ISSUE THREAD

**Issue by xdmx** [crockpotveggies/tinderbox#12]
From the console log I've noticed that few (6) faces are running infinitely. The job is processed (with the following log), then after a while a new facial analysis task is created for that same user, if finishes, and then again after a while it's scheduled again
Other profiles were correctly managed (although now I'm not getting any new profile, even I'm sure there are others that weren't swiped)

```
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] Starting new facial analysis task for 52250c214f6afeb15a000002.
[info] application - [tinderbot] Tasks queue size is currently 5
[debug] application - [updates] Fetching updates from Tinder API
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [mapdb] Database committer has persisted data to disk.
[info] application - [tinderbot] Stored 0 facial models for user 52250c214f6afeb15a000002.
[info] application - [tinderbot] Received command: run
[info] application - [tinderbot] Received command: idle
```

**Comment by crockpotveggies** [comment]
Interesting, encountered this a while ago and it's possible the bug fix I put out doesn't work anymore. It's usually caused when the foreach loop can't find a "placeholder" for existing images and then it doesn't end up storing any images because facial recognition failed (or the images were of poor quality).

The immediate fix I can think of is putting some sort of stop-gap in the DB that flags the profile. That would happen in FacialAnalysisTask.scala. It would be a while until I could have a fix, unless someone could jump in and create a PR.

**Comment by sebastianbarfort** [comment]
+1

**Comment by crockpotveggies** [comment]
Pushed an update that should address this. Make sure you pull the latest changes and note the app is being run a little differently now with the new launcher. Leave a comment if the problem persists.

**Comment by wnstnsmth** [comment]
I still have that problem, even after the update.
