### ISSUE TITLE
security warning

### ISSUE THREAD

**Issue by cometta** [crockpotveggies/tinderbox#26]
I get this message when click on auto populate token and id with both field showing empty

SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Centre for more information.

**Comment by crockpotveggies** [comment]
This is actually what is supposed to happen, and it's a good thing Facebook has that warning there. Since we need to work around the auth scheme for Tinder, you have to copy/paste your access token manually (rather than automatically since Tinder has the permissions to do so).

Closing this issue since there's no real way to make it "go away".

**Comment by KelseyDH** [comment]
Just to be clear, because the URL redirects to remove our ability to grab a token, how should we retrieve it?

**Comment by crockpotveggies** [comment]
You have to copy/paste the URL bar quickly before it does the redirect. I added a javascript function that when you paste the entire URL into "access token" field, it automatically extracts the token for convenience.

**Comment by scokiller** [comment]
I crockpotveggies !

I run tinderbox server, it work but how to get my FB token and id ? Your method don't work

**Comment by crockpotveggies** [comment]
Hi there,

Thanks for your message! As I mentioned previously on other threads all support for Tinderbox is pretty much dropped at this point since I'm dedicating my time to the successor of this project, http://www.bernie.ai/.

Bernie is well-supported, we are actively working on upgrades, and we keep up with the technical changes like the one that has caused your issue. More than happy to have you try out Bernie, otherwise you'll be on your own to support Tinderbox :)

Warmly,
Justin

**Comment by scokiller** [comment]
Hey ! Thx you for your quick reply, i'm french and i'don't speak english very well. Shit for tinderbox ! All is ready now ! Bernie is a tinderbox app mobile ! Good ! But i'm on android ! :( :( :(

Until bernie for Android came out. I can not try tinderbox ? It is no longer possible to have a facebook token ? Thank you for your reply

**Comment by crockpotveggies** [comment]
Tinderbox is nearing 2 years old and the authentication schemes have since changed. Unfortunately, the old method used to generate a token here does not work anymore. I don't think details of the newer methods are public yet.

Regarding Bernie for Android, we're about 3-4 weeks away from releasing our first Android version. You can sign up for the waitlist, we'll be keeping everyone in the loop :)

**Comment by scokiller** [comment]
You're a genius for inventing this software!
Ok I'll wait Bernie on android. But I saw that the service will be paid by subscription! What's great for you, but not for me! lol

**Comment by crockpotveggies** [comment]
Current price is $2 USD/month as of writing this comment. Yes it won't be like that forever, and we're keeping it low at this point in time so it's reasonable enough for people to try Bernie affordably. At the end of the day we need to keep the lights on so we can continue improving Bernie and making him awesome 👍
