### ISSUE TITLE
Move Config and Face Models to Fork

### ISSUE THREAD

**Issue by yourbuddyconner** [crockpotveggies/tinderbox#27]
So I've been running Tinderbox for a couple of days and I figured I'd learn play and contribute. However, I forked it and I was wondering if it was possible to move my accumulated face models from my "prod" instance to the "dev" repo on my local filesystem so it didn't have to start from scratch.

Also, do you have a list of features you think might be useful? I can think of a couple, but it's always nice to have a direction.

**Comment by crockpotveggies** [comment]
Hey thanks for playing around! To move your accumulated data, that can be easily done by copying the contents of the "data" folder and re-pasting them into the new repo. However, this could potentially break if you've removed (but not added) any new hashtables or classes to MapDB. That's because MapDB will fail to initialize if it finds a class it does not recognize.

Really appreciate the offer for features. One of the biggest the community has asked for is adding a config file that can be modified for custom messages (instead of modifying the FunMessages.scala file). I can't think of much else, except maybe a bug or two. Let me know if the migration works.
