### ISSUE TITLE
[Feature Request] Integrate super likes

### ISSUE THREAD

**Issue by xndyz** [crockpotveggies/tinderbox#92]
Would be great if Tinderbox could automatically Super Like if the attractiveness > a certain thresh hold.

**Comment by crockpotveggies** [comment]
Hi @fandy thanks for the interest in Tinderbox! As indicated in the README, support and updates for this project have been completely dropped. After the sustained interest, I've since dedicated my time into taking this into its next iteration which is http://www.bernie.ai/. Eigenfaces can only achieve so much, and therefore I've built a team to utilize deep learning and provide more than linear algebraic methods for analysis.

You're more than welcome to fork and continue maintaining this for your own personal use.

At Bernie, we're about to bring the project out of private Beta in ~month so if you need support, more features, etc., you are welcome to join us there. However, I'm glad you found some interest in this prototype that started it all!

Warmly,
Justin

**Comment by xndyz** [comment]
Sweet, I would love to contribute to Bernie.
